Catch-up-TV-and-More/plugin.video.catchuptvandmore

resources/language/resource.language.he.il/strings.po
=> Create video translation

resources/lib/channels/wo/bvn.py
See issue #113. Don't merge yet until it' actually working.
=> Add BVN.tv subtitle support

resources/lib/channels/wo/bvn.py
The previous URL no longer works
=> Update subtitle URL

resources/lib/channels/wo/bvn.py
Something I wanted to try and it looks like it's worth it.
Some rough before/after stats in seconds:
list_days before: 0.38, 0.41, 0.33
list_days after: 0.18, 0.20, 0.22
list_videos before: 0.57, 0.73, 0.71, 0.61
list_videos after: 0.30, 0.23, 0.23, 0.24
=> Stop using beautifulsoup

addon.xml, resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.fr_fr/strings.po, resources/language/resource.language.he_il/strings.po, resources/language/resource.language.nl_nl/strings.po
Now that we have Dutch channels...
=> Add Dutch translation

resources/lib/channels/nl/npo.py
=> API key change

plugin.video.catchuptvandmore/resources/lib/channels/it/raiplay.py
Test stream: Replay TV > Italie > Rai Play > R > Raffaello Il genio sensibile.
Thanks.
=> [raiplay.py] Play subtitles if available.

plugin.video.catchuptvandmore/resources/lib/channels/us/abcnews.py
Petite contribution avant ma semaine de vacances :) .
=> Abcnews no items

plugin.video.catchuptvandmore/resources/lib/channels/be/vrt.py
J'espère que ça passera Flake8 cette fois ;-) .
Juste pour info, quelle est la valeur utilisée pour le nombre de caractères par ligne ?
=> Fix <No item found> error in replay tv

plugin.video.catchuptvandmore/resources/lib/channels/uk/sky.py
Encore un petit PR.
Bonne nuit cette fois  :grin:  .
=> Fix http 404 error with Skysports UK

plugin.video.catchuptvandmore/resources/lib/websites/allocine.py
Bonjour à tous,
Voici un petit PR qui fixe partiellement la recherche dans Allociné : elle ne fonctionne provisoirement qu'avec la rubrique "Vidéos".
J'aimerais l'étendre aux autres catégories, mais ça nécessitera un peu plus de travail.
Je mets le PR en draft, en attendant votre avis sur l'opportunité de le merger en l'état ou d'attendre la suite...
Passez un excellent weekend :wink: .
=> Fix broken search with Allociné

plugin.video.catchuptvandmore/resources/lib/channels/be/rtbf.py
Hls doesn't work anymore for replay so replace with mpd
=> Update replay rtbf

plugin.video.catchuptvandmore/resources/lib/websites/nytimes.py
Un petit PR, j'espère que tout roule...
Cordialement.
=> Fix New York Times "404 error".

plugin.video.catchuptvandmore/resources/lib/channels/be/rtbf.py
Bonjour,
Petit fix pour l'erreur "Http 400" sur RTBf Auvio.
Le programme essayait de jouer certaines vidéos sans drm comme des vidéos avec drm...
Bon weekend à tous,
[fix #360]
=> Fix Rtbf Auvia Http 400 error.

plugin.video.catchuptvandmore/resources/lib/resolver_proxy.py
Modification de resolver_proxy.py pour l'adapter à la nouvelle api drm de France TV.
Cette modification n'a pu être testée qu'avec une seule série (Les enquêtes de Murdoch), faute d'autres candidats.
À retester donc dès que d'autres émissions protégées par drm auront été identifiées...
=> Mise à jour de France TV pour l'api drm.

plugin.video.catchuptvandmore/resources/lib/channels/be/rtbf.py
Lorsqu'il n'y avait pas de DRM sur le fichier, celà plantait, j'ai donc fixé ça
=> Fix issues with file without drm

plugin.video.catchuptvandmore/resources/lib/channels/fr/6play.py
- Improve quality for 6play catch-up and live TV
- Increase number of available 6play programs
=> 6play improvements

plugin.video.catchuptvandmore/resources/lib/channels/be/rtbf.py
Dash aren't working anymore so back to hls for the moment
Fix #402
=> Update RTBF to fix dash issue

plugin.video.catchuptvandmore/resources/language/resource.language.en_gb/strings.po, plugin.video.catchuptvandmore/resources/language/resource.language.fr_fr/strings.po, plugin.video.catchuptvandmore/resources/language/resource.language.he_il/strings.po, plugin.video.catchuptvandmore/resources/language/resource.language.nl_nl/strings.po, plugin.video.catchuptvandmore/resources/lib/iptvmanager.py, plugin.video.catchuptvandmore/resources/lib/xmltv.py, plugin.video.catchuptvandmore/resources/settings.xml
This PR add the first and initial support for IPTV Manager.
Next things to do:
* Wiki and official website documentation
* Multi-lingual channels support
See #400 for more information.
=> Add IPTV Manager support

resources/lib/channels/be/hln_live.py, resources/lib/skeletons/be_live.py, resources/m3u/live_tv_all.m3u, resources/m3u/live_tv_be.m3u
This adds the HLN Live channel from their own website.
=> Add HLN Live

.gitattributes, .pylintrc, Makefile, requirements.txt
This Makefile helps to run checks, tests or make a ZIP file.
Not everything will work now, a few future PRs will add missing checks
and tests.
=> Add a Makefile

resources/lib/download.py, resources/lib/resolver_proxy.py
Take advantage of recent changes in script.module.youtube.dl.
Allow download of dash files that are not DRM-protected.
=> Enhance download capability

resources/lib/channels/be/robtv.py, resources/lib/skeletons/be_replay.py
* Add video on demand content for ROBTV
=> Add VOD for ROBTV

resources/lib/channels/fr/equidia.py, resources/lib/skeletons/fr_live.py
Hi,
I'm proposing to add Equidia racing channels.
I edited the way Equidia live stream is resolved using the API used by Equidia mobile app. And therefore I changed Equidia item_id in the skeleton file to match the one used in the API url
=> Add equidia racing channels

resources/lib/channels/fr/francetvsport.py
Les lives de Roland Garros n'apparaissent pas dans la section francetv sport (Il n'y a que les videos tagged prochainement)
Avec ces modifications  j'arrive à avoir les lives disponibles sur le site francetv.
=> Fix France TV Sport Lives

resources/lib/channels/it/mediaset.py, resources/lib/channels/nl/ob.py, resources/lib/skeletons/it_live.py, resources/lib/skeletons/nl_live.py
Added the Dutch live TV channel Omroep Brabant and the Italian live TV channels of Mediaset.
=> Added Omroep Brabant live (NL) and Mediaset Live (IT)

resources/lib/channels/be/rtlplaybe.py
add RTL play menu
Les exclu RTL play ne sont pas présentes dans les autres chaînes.
=> add rtl play menu

resources/lib/resolver_proxy.py
Based on fix by @0xced submitted in PR #550, also fix issue for HLS streams.
Fixes #540
=> Fix france tv replay for HLS streams

resources/lib/channels/ch/srgssr.py
=> Fix error on SSR channels replay.

resources/lib/channels/fr/alsace20.py, resources/lib/channels/fr/lachainenormande.py
Affected files : alsace20.py and lachainenormande.py.
See issue #584.
=> Remove deprecated item property "inputstreamaddon".

resources/lib/channels/it/raiplay.py, resources/lib/skeletons/it_replay.py
General enhancement of raiplay.tv: new root menu, direct access to "homepage" categories and search feature.
=> Enhanced raiplay

resources/lib/channels/be/rtlplaybe.py
[BE - RTLPlay] add 'All programs'
New menu to list all programs by first letter.
Some programs were not available in the categories, only in 
https://www.rtlplay.be/tous-les-programmes
=> [BE - RTLPlay] add 'All programs'

resources/lib/channels/be/rtc.py
=> [BE - RTC] fix missing schema

resources/lib/channels/uk/uktvplay.py
UKTV Play is currently broken due to the error cited above.
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/541#issuecomment-984091003
=> UKTV Play: Fix local variable 'data_account' referenced before assignment

.gitignore, resources/lib/channels/jp/ntvnews24.py
=> [JP - ntvnews24] fix live url

.github/ISSUE_TEMPLATE/bug_report.md
=> fix bug report

resources/lib/channels/be/rtlplaybe.py, resources/lib/channels/fr/6play.py
Liste des changements de ce pull request
J'ai testé le live M6 et RTLPlay avec choix de qualité et le search RTLPlay
Quelqu'un peut confirmer que c'est OK pour le menu "tous les programmes" de M6? 
J'ai testé les menus avec [catchuptvandmore-test](https://github.com/Catch-up-TV-and-More/catchuptvandmore-test) et kodi.
Par contre, je n'arrive pas à lancer les vidéos, erreur 403.
Je suis en Belgique et je n'ai pas les accès au replay M6.
=> [BE - RTLPlay] [FR - M6] choose live quality, [FR - M6] all programs, [BE - RTLPlay] add search

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.fr_fr/strings.po, resources/language/resource.language.he_il/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/channels/fr/rmcbfmplay.py, resources/settings.xml
- Ajout de la gestion du compte.
- Correction de la génération de l'autorisation.
- Début Podcast (il reste que le code de Spotify à faire).
- Nettoyage de la génération du menu.
- Tous semble fonctionner.
Le drm marche uniquement sous Android, probablement à cause de VMP.
Et il reste aussi à implémenter le flux live des chaines.
=> Suite rmcbfmplay

resources/lib/channels/es/rtve.py
Hi all, first thanks for the incredible kodi addon! When i tried to access RTVE live stream, it delivered always the short buggy sequence.
Found on their website an updated link, tested it on kodi for ubuntu, it works.
=> [ES Live RTVE] Fix broken live url

resources/lib/channels/it/radiofreccia.py, resources/lib/skeletons/it_live.py
[IT - Radiofreccia] add Radiofreccia Web TV
=> [IT - Radiofreccia] Add Radiofreccia Web TV

resources/lib/channels/fr/mycanal.py
Just some code cleanup to reduce the number of useless line.
=> [FR - MYCANAL] Code cleanup

resources/lib/channels/it/radiofreccia.py
[IT - Radiofreccia] Make it work without inputstream.adaptive
=> [IT - Radiofreccia] Make it work without inputstream.adaptive

resources/lib/channels/be/tvlux.py
=> [BE - TV Lux] Fix live

resources/lib/channels/wo/euronews.py
New address for JSON to fix live tv
=> [WO - EURONEWS] Update Euronews link

resources/lib/channels/be/tvlux.py
[BE - TV Lux] Small pattern fix
=> [BE - TV Lux] Small pattern fix

resources/lib/channels/fr/mycanal.py
=> [FR - MyCanal] Fix flake8

resources/lib/channels/it/radiofreccia.py
[IT - Radiofreccia] Choose quality without inputstream.adaptive
=> [IT - Radiofreccia] Choose quality without inputstream.adaptive

resources/lib/channels/it/rtl.py, resources/lib/skeletons/it_live.py
[IT - RTL 102.5] Add radio lives
fixes #704
see also 
https://github.com/Catch-up-TV-and-More/resource.images.catchuptvandmore/pull/13
for pictures
=> [IT - RTL 102.5] Add radio lives

resources/lib/channels/it/rtl.py
[IT - RTL 102.5] Add radio lives - get_live_url change
=> [IT - RTL 102.5] Add radio lives - get_live_url change

resources/lib/channels/be/telemb.py
=> [BE - Télé MB] Fix live

resources/lib/channels/it/rtl.py
[IT - RTL 102.5] Extract video URL using “YouTube.DL” without input stream adaptative
=> [IT - RTL 102.5] Extract video URL using “YouTube.DL” without input stream adaptative

resources/lib/channels/be/vrt.py
=> [BE - VRT] Fix live

resources/lib/channels/be/abbe.py, resources/lib/channels/be/telemb.py, resources/lib/channels/be/vrt.py
[BE - AB] Check widevine
[BE - VRT] Check widevine
[BE - Télé MB] Refactoring in resolver_proxy.py
=> Check widevine & refactoring

requirements.txt, resources/lib/channels/be/bouke.py, resources/lib/skeletons/be_replay.py
=> [BE - Bouke] Add replay

resources/lib/channels/it/rtl.py
[IT - RTL 102.5] Copyright correction
=> [IT - RTL 102.5] Copyright correction

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.fr_fr/strings.po, resources/language/resource.language.he_il/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/channels/wo/tv5mondeplus.py, resources/settings.xml
[WO - TV5MONDEPLUS] Add search, Use GeoIp country, random user agent, language
=> [WO - TV5MONDEPLUS] Add search, Use GeoIp country, random user agent, language

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.fr_fr/strings.po, resources/language/resource.language.he_il/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/settings.xml
Settings - Add InputStream adaptive settings link
=> Settings - Add InputStream adaptive settings link

resources/lib/channels/be/rtbf.py
[BE - RTBFAuvio] Allow using input stream adaptive
=> [BE - RTBFAuvio] Allow using input stream adaptive

resources/lib/channels/be/bouke.py
[BE - Bouke] Fix images and thumbs
=> [BE - Bouke] Fix images and thumbs

resources/lib/channels/wo/tv5mondeplus.py, resources/lib/skeletons/wo_replay.py
[WO - TV5MONDEPLUS] Fix missing description, add images
ajouter également l'image de 
https://github.com/Catch-up-TV-and-More/resource.images.catchuptvandmore/pull/17
=> [WO - TV5MONDEPLUS] Fix missing description, add images

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.fr_fr/strings.po, resources/language/resource.language.he_il/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/settings.xml
=> [Project] settings changes

resources/lib/addon_utils.py, resources/lib/channels/be/rtlplaybe.py, resources/lib/channels/ch/lemanbleu.py, resources/lib/channels/ch/lfmtv.py, resources/lib/channels/es/mitele.py, resources/lib/channels/fr/6play.py, resources/lib/channels/fr/bfmtv.py, resources/lib/channels/fr/franceinfo.py, resources/lib/resolver_proxy.py, resources/lib/streams/m3u8.py
[Project] Qualities as enum - fix comparison
=> [Project] Qualities as enum - fix comparison

resources/lib/channels/es/mitele.py
[ES - MITELE] Fix typos and undeclared values
=> [ES - MITELE] Fix typos and undeclared values

resources/lib/channels/be/ln24.py, resources/lib/skeletons/be_replay.py
=> [BE - LN24] Add replay

resources/lib/channels/fr/weo.py, resources/lib/resolver_proxy.py
[FR - WEO] Fix live
- resolver_proxy.py : make __get_non_ia_stream_with_quality private again
- regexp correction, string replace correction
- fix local variable 'video_page' might be referenced before assignment
- fix flake8
=> [FR - WEO] Fix live

resources/lib/channels/be/nrjhitstvbe.py, resources/lib/resolver_proxy.py, resources/lib/skeletons/be_live.py, resources/lib/streams/m3u8.py
[BE - NRJ] Fix live, Fix replay
- Fix #741
=> [BE - NRJ] Fix live, Fix replay

resources/lib/channels/ma/snrt.py
Not very staisfied by this solution. But, retrieving the URL by intermdiate site produces many redirections to forbidden sites.
=> [MA - SNRT] Fix lives

resources/lib/resolver_proxy.py
resolver_proxy.py disable context related
=> resolver_proxy.py disable context related

resources/lib/resolver_proxy.py
[Project] Use get_stream_with_quality in more places
=> [Project] Use get_stream_with_quality in more places

resources/lib/channels/fr/mycanal.py
Added support for the official livestream on mycanal.
That will improve the stability on the long run.
A lot of code use on this commit was initially made by @mtr81.
I have just made some change to made it more flexible.
=> [FR - MYCANAL] Use other links for lives

resources/lib/channels/us/abcnews.py
This commit fix every menu except when they need a cable account.
=> [US - ABCNEWS] Partially fix #140

resources/lib/channels/tr/show.py, resources/lib/skeletons/tr_live.py
Avec tant bien que mal, voici une PR qui devrait être bon.
J'ai une dizaine d'autres chaînes que j'aimerais ajouter j'espère ne pas trop spam
=> [TR - Show TV] Add channel

resources/lib/channels/tr/haberglobal.py, resources/lib/channels/tr/tv8.py, resources/lib/skeletons/tr_live.py
Salut ! il me reste encore un bon paquet de chaine a ajouter et j'ai l'impression que ça va jamais en finir haha, peut-on partir plutôt sur **une dernière PR avec pour chaque commit une seule chaîne** ajouté ?
Pour l'ordre des chaînes j'aimerais partir sur **une liste dans un ordre "naturel" et non pas sur un ordre alphabétique** ^^ (un peu comme la liste des chaînes française)
J'aimerais également savoir si vous avez un discord ou bien un telegram sur lequel on peut parler j'aurais quelque question sur le fonctionnement du plugin
=> [TR - Haber Global] Add Channel & Fix [TR - TV8]

resources/lib/channels/tr/bloomberght.py
Petit oublie de ma part, je viens de recheck et il y a deux div avec la même classe, c'est fix !
=> [TR - Bloomberg] Fix

resources/lib/channels/tr/kanald.py
J'ai ajouté un user-agent afin de faire fonctionner le live, le lien était correcte mais ne fonctionnait pas sans.
=> [TR - Kanal D] Added custom headers

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.fr_fr/strings.po, resources/language/resource.language.he_il/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/channels/wo/tv5monde.py, resources/settings.xml
[WO- TV5MONDE] TV5Monde live outside FBS
- fix #802
=> [WO- TV5MONDE] TV5Monde live outside FBS

resources/lib/resolver_proxy.py
Looks like the version 1 of Arte API does not work anymore
=> [WO - ARTE] Fix replay

resources/lib/skeletons/tr_live.py
@joaopa00 Peux-tu en profiter pour release une beta s'il te plait ? Il me reste quelque dernière chaine à ajouter mais je viens de recevoir mon fire stick et j'aimerais bien pouvoir profiter des autres chaines que j'ai ajouté entre temps ^^
=> [TR - MINIKA GO] Add channel

resources/lib/channels/tr/dogus.py, resources/lib/skeletons/tr_live.py
Voici ma dernière PR ! Normalement j'ai rien de plus à ajouter pour l'instant haha
=> [TR - DOGUS] Added Dogus group channels

resources/lib/channels/be/rtbf.py
=> [BE - RTBFAuvio] Limit bitrate for live and drm stream

resources/lib/channels/uk/stv.py, resources/lib/resolver_proxy.py
[UK - STV] Fix Catch up fails with "Type Error"
- fixe une partie de #812
=> [UK - STV] Fix Catch up fails with "Type Error"

resources/lib/channels/be/rtbf.py
[BE - RTBFAuvio] Paginate list_videos_category
=> [BE - RTBFAuvio] Paginate list_videos_category

resources/lib/addon_utils.py, resources/lib/channels/fr/mycanal.py, resources/lib/channels/wo/tv5monde.py, resources/lib/enum/LICENSE, resources/lib/enum/README, resources/lib/enum/__init__.py
[Project] make Enum compatible with python 2.7 and kodi 18.x
- partial fix for #830
=> [Project] make Enum compatible with python 2.7 and kodi 18.x

resources/lib/websites/nytimes.py
[Website - NYTIMES] Fix fails to open, with error: KeyError 'data'
- fix #844
=> [Website - NYTIMES] Fix fails to open, with error: KeyError 'data'

resources/lib/channels/fr/antennereunion.py
[FR - antennereunion] Fix live and replay
- see #737
=> [FR - antennereunion] Fix live and replay

resources/lib/skeletons/websites.py, resources/lib/websites/veely.py
[Website - VEELY] Add live and replay
- to merge: https://github.com/Catch-up-TV-and-More/resource.images.catchuptvandmore/pull/26
- Fix #850
=> [Website - VEELY] Add live and replay

resources/lib/websites/veely.py
[Website - VEELY] Add seasons, episodes and duration
=> [Website - VEELY] Add seasons, episodes and duration

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.fr_fr/strings.po, resources/language/resource.language.he_il/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/skeletons/websites.py, resources/lib/websites/sonuma.py
=> [Website - SONUMA] Add site

resources/lib/websites/sonuma.py
[Website - SONUMA] Better management of empty lists
=> [Website - SONUMA] Better management of empty lists

resources/lib/channels/wo/euronews.py, resources/lib/skeletons/wo_live.py, resources/settings.xml
[WO - Euronews] Add Romania live
- fix #868
=> [WO - Euronews] Add Romania live

resources/lib/websites/sonuma.py
[Website - SONUMA] Fix next page thematique
=> [Website - SONUMA] Fix next page thematique

resources/lib/channels/fr/lci.py
=> [FR - LCI] Fix replay

resources/lib/channels/be/matele.py, resources/lib/skeletons/be_live.py
[BE - MATELE] Add live
- fix #881
- see here for images to merge https://github.com/Catch-up-TV-and-More/resource.images.catchuptvandmore/pull/33
=> [BE - MATELE] Add live

resources/lib/menu_utils.py
[Project] add vpn context
- add VPN context for #870
=> [Project] add vpn context

resources/lib/channels/be/rtbf.py
[BE - RTBF] Fix error when url_embed is missing
=> [BE - RTBF] Fix error when url_embed is missing

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.fr_fr/strings.po, resources/language/resource.language.he_il/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/channels/be/rtbf.py, resources/settings.xml
[BE - RTBF] adapt for new stream provider (redbee)
- fix #920
=> [BE - RTBF] adapt for new stream provider (redbee)

resources/lib/channels/be/ln24.py
[BE - LN24] Fix live
- fix #925
=> [BE - LN24] Fix live

resources/lib/channels/be/rtbf.py
[BE - RTBF] Adapt live for new stream provider (redbee
- fixe #920
=> [BE - RTBF] Adapt live for new stream provider (redbee

resources/lib/channels/be/rtbf.py
Hello,
I've improved the live and now DRM can be streamed on RPI..it needs to be checked if it works as well on other platform otherwise we'll need to find a way to find the arch to fix it.
For the live, as it has a different url for each live it's no more possible to get it on the PVR...I don't knwo why but when using the PVR it always take the cached json even with the max_cache set to -1.
You need to go to RTBF auvio folder in the live to get it works. If anyone can fix it would be good, otherwise the skeleton file will need to be updated and the channel will need to be deactivated for the live and just leave the RTBF auvio folder.
fix issue #935 https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/935
=> Fix live and issue with drm on rpi

resources/lib/channels/be/rtbf.py
=> fix flake8

resources/lib/channels/be/rtbf.py
[BE - RTBF] Adapt live for new stream provider (redbee) - fix replays in categories
=> [BE - RTBF] Adapt live for new stream provider (redbee) - fix replays in categories

resources/lib/channels/be/rtlplaybe.py
[BE - RTLPLAYBE] make search work again in kodi >=19
=> [BE - RTLPLAYBE] make search work again in kodi >=19

resources/lib/channels/be/rtlplaybe.py
[BE - RTLPLAYBE] yield playlist
=> [BE - RTLPLAYBE] yield playlist

resources/lib/channels/fr/6play.py, resources/lib/channels/fr/tv7bordeaux.py
=> [FR - M6] yield playlist

resources/lib/channels/fr/mycanal.py
Fix https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/947
=> [FR - Mycanal] Fix index error

resources/lib/channels/fr/cnews.py, resources/lib/channels/fr/tv7bordeaux.py
[FR - CNEWS] Fix #943 Cnews replay
=> [FR - CNEWS] Fix #943 Cnews replay

resources/lib/channels/ca/tva.py
[CA - TVA] fix replay
draft: I don't have a VPN to test
=> [CA - TVA] fix replay

resources/lib/channels/ca/tva.py
[CA - TVA] fix replay - api change
- fix #954
=> [CA - TVA] fix replay - api change

resources/lib/channels/ca/tva.py
=> [CA - TVA] Fix live

resources/lib/channels/ca/telequebec.py, resources/lib/skeletons/ca_replay.py
[CA - telequebec] Add section "En vedette" in replay (films, ...)
=> [CA - telequebec] Add section "En vedette" in replay (films, ...)

resources/lib/channels/be/ln24.py
[BE - LN24] Fix some replays
some replays are not working
new html with an iframe for new videos.
Example: OK
- 2  📁   Catch-up TV  
- 5  📁   Belgium   
- 13 📁   LN24  
- 24 📁   Qu'est-ce qu'on regarde ce soir?   
- 3  ▶   "La nuit du 12": ces "cold case...lges    
Example KO:
- 2  📁   Catch-up TV  
- 5  📁   Belgium   
- 13 📁   LN24  
- 24 📁   Qu'est-ce qu'on regarde ce soir?   
- 2  ▶   Pourriez-vous vous passer de vo...ois?
=> [BE - LN24] Fix some replays

resources/lib/channels/fr/franceinfo.py
The "lastPublicationDate" field in the json return the wrong date sometimes. It's better to use the "firstPublicationDate" field to have an accurate display in Kodi.
=> [FR - Franceinfo) Fix aired date

resources/lib/channels/be/rtbf.py
[BE - RTBF] Better handling of search without result
=> [BE - RTBF] Better handling of search without result

resources/lib/channels/be/telesambre.py, resources/lib/skeletons/be_replay.py
=> [BE - TELESAMBRE] Add replay

resources/lib/websites/allocine.py
- Add date and synopsis for the search result.
- Get a list of every content that related to a movie.
- Simplifies video detection.
- Fix base64 decryption.
- Add next page for the program list.
=> [FR - Allocine] Begin rework

resources/lib/channels/fr/mytf1.py
Fix : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/917
=> [FR - Mytf1] Fix US replay

resources/lib/channels/be/atv.py, resources/lib/channels/be/robtv.py, resources/lib/channels/be/tvl.py, resources/lib/channels/be/tvoost.py
A new PR to fix merge conflicts
=> update urls for atv, robtv, tvl, tvoost

resources/lib/channels/nl/npo.py
Should allow NPO to be taken off the list of known issues again
=> Fix NPO 'NoneType' is not iterable error

resources/lib/channels/be/ln24.py, resources/lib/channels/be/nrjhitstvbe.py, resources/lib/channels/be/rtbf.py, resources/lib/channels/be/telesambre.py, resources/lib/channels/ca/tva.py, resources/lib/channels/wo/tv5mondeplus.py, resources/lib/websites/sonuma.py, resources/lib/websites/veely.py
[BE - RTBF] Fix replay
case not working before fix:
2  📁   Catch-up TV
5  📁   Belgium
6  📁   RTBF Auvio
9  📁   Documentaires
5  📁   Investigation
4  ▶   #Investigation - CPAS :...rnal
=> [BE - RTBF] Fix replay

resources/lib/channels/be/rtbf.py, resources/lib/resolver_proxy.py
[BE - RTBF] refactoring to remove code duplication and drm fix
=> [BE - RTBF] refactoring to remove code duplication and drm fix

resources/lib/channels/wo/euronews.py
[WO - EURONEWS] Fix live
- fix #1011
=> [WO - EURONEWS] Fix live

resources/lib/resolver_proxy.py
- fix #1021 regression from commit 1aa1ac1
=> fix regression from commit 1aa1ac1

resources/lib/channels/it/rtl.py
[IT - RTL 102.5] fix lives
- fix #1024
=> [IT - RTL 102.5] fix lives

resources/lib/channels/be/rtbf.py, resources/lib/channels/fr/la_1ere.py
=> [BE - RTBF] drm fix

resources/lib/channels/wo/tv5monde.py
[WO - tv5monde] Fix enum regression from 56cee80a
=> [WO - tv5monde] Fix enum regression from 56cee80a

resources/lib/channels/be/rtbf.py
=> [BE - RTBF] cleanup imports

resources/lib/channels/wo/aljazeera.py, resources/lib/skeletons/wo_live.py
[WO - Aljazeera] Add lives
- partial fix of #1030
- to merge with https://github.com/Catch-up-TV-and-More/resource.images.catchuptvandmore/pull/38
=> [WO - Aljazeera] Add lives

resources/lib/channels/be/rtbf.py
[BE - RTBF] Fix play for search items with DRM
example not working before:
- 2     Catch-up TV   
- 5    Belgium 
- 6     RTBF Auvio   
- 2    Search programs
- 1    [B]Search[/B] 
- Grand cactus
- 1     Le Grand Cactus  
- 2     Le Grand Cactus - Avec ...ise!
=> [BE - RTBF] Fix play for search items with DRM

resources/lib/channels/fr/6play.py
[FR - M6] Fix API_KEY
-Fix #1039
=> [FR - M6] Fix API_KEY

resources/lib/resolver_proxy.py
[FR - FRANCETV] Fix live for FranceInfo  - part2
=> [FR - FRANCETV] Fix live for FranceInfo

resources/lib/channels/wo/tv5mondeplus.py
[WO - TV5MONDEPLUS] Fix DRM license
- Fix #1036
=> [WO - TV5MONDEPLUS] Fix DRM license

.github/ISSUE_TEMPLATE/bug_report.md, README.md
=> [PROJECT] Bug report template

resources/lib/channels/fr/mytf1.py
L'identité de la recherche de vidéos n'était pas la bonne
=> [FR - MYTF1] Fix replay

resources/lib/channels/uk/my5.py, resources/lib/skeletons/uk_replay.py
offset lines appear to work
extra () removed
=> Add UK my5 (Channel 5) To Dev branch

resources/lib/channels/uk/my5.py, resources/lib/skeletons/uk_live.py
Added live playback for UK My5 (Channel5), 
checks for list items where count is different to items listed  - range(item_number) is bigger than actual items listed
params for PLC_My5AllShows were being updated incorrectly
=> [UK - MY5] Activated Live and minor bug fixes

resources/lib/channels/be/rtbf.py
sometimes like tonight, there is no drm in video_format from redbee so it was crashing. This fix the error
=> fix crash if no drm in video format

resources/lib/resolver_proxy.py
Ça semble être la manière la plus simple de ne pas se prendre la tête.
=> [FR - France] Fix catchup

resources/lib/channels/be/rtbf.py
[BE - RTBF] small fix for m3u8
=> [BE - RTBF] small fix for m3u8

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.fr_fr/strings.po, resources/language/resource.language.he_il/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/channels/fr/mytf1.py, resources/settings.xml
[FR - TF1] DRM and login
- fix #1162
J'ai fait une pull request pour les replays.
Je ne peux pas tester pour les lives avec le blocage géographique en Belgique, mais la même technique devrait fonctionner 
(réutiliser la méthode resources.lib.channels.fr.mytf1.get_token)
=> [FR - TF1] DRM and login

resources/lib/channels/be/canalzoom.py, resources/lib/channels/be/ln24.py
[BE - LN24] fix live
[BE - canalzoom] fix live
=> [BE] fix lives

resources/lib/channels/fr/mycanal.py, resources/lib/resolver_proxy.py
[FR - MYCANAL] use get_stream_with_quality
=> [FR - MYCANAL] use get_stream_with_quality

resources/lib/resolver_proxy.py
[PROJECT] resolver_proxy : python 2 compatibility
- fix #1189
=> [PROJECT] resolver_proxy : python 2 compatibility

addon.xml, resources/lib/channels/pl/tvp.py, resources/lib/skeletons/pl_live.py
No PL TVP LIVE channel was working anymore following updates of TVP website.
Some channels could be fixed :
- TVP 3 (every regions)
- TVP World
Some deleted
- TVP Info
- TVP Polonia
Some added
- TVP Alfa
- UA 1
Some might be added, but are also not working :
- TVP 1
- TVP 2
=> [PL - TVP] Fix or add few PL TVP live channels

resources/lib/channels/fr/6play.py
[FR - 6PLAY] fix KeyError
- fix #1206
=> [FR - 6PLAY] fix KeyError

resources/lib/resolver_proxy.py
[PROJECT] update resolver_proxy.py
=> [PROJECT] update resolver_proxy.py

resources/lib/channels/wo/bvn.py
[WO - BVN] fix live
- fix #1215
=> [WO - BVN] fix live

resources/lib/channels/be/rtbf.py
=> [BE - RTBF] new search API

resources/lib/channels/be/rtlplaybe.py, resources/lib/skeletons/be_live.py
[BE - RTLPLAY] Fix live and replays
- lié à #1221
=> [BE - RTLPLAY] Fix live and replays

resources/lib/skeletons/be_live.py
[BE - RTLPLAY] Disable rtl_sport
RTL sport n'est plus disponible sur le site
=> [BE - RTLPLAY] Disable rtl_sport

resources/lib/channels/pl/tvpvod.py, resources/lib/skeletons/pl_replay.py, resources/lib/skeletons/replay.py
Add kids content from PL TVP VOD
Note : Limited support : 
- Only cartoons.
- No authentication supported.
=> [PL - TVP VOD] Add kids content from PL TVP VOD

resources/lib/channels/pl/playpuls.py, resources/lib/skeletons/pl_replay.py
Add kids replay content from Play Puls
Images added with : https://github.com/Catch-up-TV-and-More/resource.images.catchuptvandmore/pull/43
=> [PL - Play Puls] Add kids replay content from Play Puls

resources/lib/channels/uk/uklocaltv.py, resources/lib/skeletons/uk_live.py
Wales the country, not the creature
=> Fix typo (Whales -> Wales)
