Catch-up-TV-and-More/plugin.video.catchuptvandmore

resources/lib/root/channels/wo/bvn.py

`live_jsonparser["hls"]` already includes the `http:` part

Correct BVN live URL

---

resources/lib/channels/fr/francetv.py

Plenty of details are available in the JSON we already request. So without an additional load, we can provide much more info in the details of each broadcast.
Details in particular:
- cast and roles, considering the presenter as part of the cast
- rating
- season and episode
- director
In the same go I tried to reduce duplicate code a bit by putting the common part of `list_videos` and `list_videos_last` into a separate function.
With season and episode in place we have a way to distinguish the different episodes, where often programs display the identical broadcast dates or nothing at all. The added bonus is that you can sort the video list by episode(/season) now.
The interesting bit is where `item.info['mediatype'] = "episode"` is being applied now. This is needed to not have those …

Use more details for France-*

---

resources/lib/channels/wo/bvn.py

Prevents "unable to resolve URL" errors when trying to play the same video more than once.

Fixed playing video more than once

---

resources/lib/channels/wo/bvn.py

At first I did not want to bother checking how long a token is really valid, so I forced it to not being cached at all.
Out of interest, however, and with using this add-on in practice, every call less is already a speed gain.
Tokens are valid for an hour. The timer appears to be reset after each subsequent use (URL_VIDEO_REPLAY), but just keeping it for an hour in total is already better than nothing.

Reuse token for an hour

---

resources/lib/channels/wo/bvn.py

Apparently in some cases a new broadcast is already listed but can't actually be played yet when you try to do so too soon. At least this will tell you what's going on instead of returning a technical error.

Add stream not available error

---

resources/lib/channels/fr/6play.py

now we can for sample "add m6\capital\all vid" to addon favourites.

add a missing item_post_treatment for allvid item

---

resources/lib/resolver_proxy.py
resources/settings.xml

This adds support for specifying an `X-Forwarded-For` header when making requests which can be used to bypass geo restriction on some video providers.
This was tested on Brightcove with the tver.jp channel ([sample episode](https://tver.jp/corner/f0041182)).

Add X-Forwarded-For setting

---

addon.xml
resources/lib/favourites.py
resources/lib/listitem_utils.py
resources/lib/main.py

Hey @wwark (et éventuellement @Psychoses),
Ce PR permet (normalement) de stocker les favoris dans un JSON à la place du fichier pickle.
J'ai essayé en XML mais trop la galère ...
Normalement j'ai aussi fait en sorte que la migration des favoris existant puisse se faire, mais ce point est encore à confirmer ...
Est-ce que si vous avez des favoris existants vous pouvez essayer le test suivant :
1. **Faire un backup du fichier `favourites.pickle`**
2. Appliquer la branche `favourites_json`
3. Accéder à vos Favoris (ou bien ajouter un nouveau favoris)
4. Remarquer que le fichier `favourites.pickle` a été supprimé et qu'un nouveau fichier `favourites.json` a été créé et contient vos anciens favoris
5. Essayer de jouer un peu avec les favoris (Ajouts, suppressions, renommage, Monter, Descendre, …

Use JSON file for Favourites instead of pickled data

---

plugin.video.catchuptvandmore/resources/lib/channels/be/rtbf.py
plugin.video.catchuptvandmore/resources/lib/labels.py
plugin.video.catchuptvandmore/resources/lib/skeletons/be_live.py
plugin.video.catchuptvandmore/resources/m3u/live_tv_all.m3u
plugin.video.catchuptvandmore/resources/m3u/live_tv_be.m3u

Hello,
I wanted to be able to get the main auvio TV channels in the TV Guide (La Une, La Deux and La Trois), so I have changed the files to have a live_bridge for auvio main TV channels. So they are now directly in the be folder and in the auvio folder. I have kept the auvio folder because it contains exclusive contents and live radio channel.
For the change to work, it will request to load as well the channels images in the https://github.com/Catch-up-TV-and-More/images repository 
You can find the channel pictures here: http://www.rtbf.be/api/partner/generic/epg/channellist?v=7&type=tv&partner_key=82ed2c5b7df0a9334dfbda21eccd8427
In the different files I've named the pictures laune.jpg and laune_fanart.jpg (same for other channels but with ladeux and latrois)
Let me know what you think …

Add auvio main TV channels

---

plugin.video.catchuptvandmore/resources/lib/channels/fr/publicsenat.py

Fix page : We need start at "0" for don't miss the first page videos.
Fix list_texts[2].text : list_texts[2].text can be a NoneType and make concatenation fail.

Fix page and list_texts[2].text

---

plugin.video.catchuptvandmore/resources/lib/channels/it/raiplay.py

Bonjour,
L'api de *raiplay.it* ayant changé, les vidéos en replay ne sont plus ni affichables ni jouables.
Les changements dans l'api sont toutefois mineurs (noms des objets json en particulier) et les modifications apportées à *raiplay.py* sont donc minimes également.
Merci d'avance.
**Edit** : *raiplay.it* est géolocalisé malheureusement.

Fix raiplay.py accordingly to the new api.

---

plugin.video.catchuptvandmore/resources/lib/channels/fr/france3regions.py
plugin.video.catchuptvandmore/resources/lib/channels/fr/la_1ere.py
plugin.video.catchuptvandmore/resources/lib/channels/wo/arte.py
plugin.video.catchuptvandmore/resources/lib/channels/wo/cgtn.py
plugin.video.catchuptvandmore/resources/lib/channels/wo/dw.py
plugin.video.catchuptvandmore/resources/lib/channels/wo/euronews.py
plugin.video.catchuptvandmore/resources/lib/channels/wo/nhkworld.py
plugin.video.catchuptvandmore/resources/lib/channels/wo/qvc.py
plugin.video.catchuptvandmore/resources/lib/channels/wo/rt.py
plugin.video.catchuptvandmore/resources/lib/main.py
plugin.video.catchuptvandmore/resources/lib/skeletons/wo_live.py
plugin.video.catchuptvandmore/resources/m3u/live_tv_all.m3u
plugin.video.catchuptvandmore/resources/m3u/live_tv_be.m3u
plugin.video.catchuptvandmore/resources/m3u/live_tv_ca.m3u
plugin.video.catchuptvandmore/resources/m3u/live_tv_ch.m3u
plugin.video.catchuptvandmore/resources/m3u/live_tv_cm.m3u
plugin.video.catchuptvandmore/resources/m3u/live_tv_cn.m3u
plugin.video.catchuptvandmore/resources/m3u/live_tv_es.m3u
plugin.video.catchuptvandmore/resources/m3u/live_tv_et.m3u
plugin.video.catchuptvandmore/resources/m3u/live_tv_fr.m3u
plugin.video.catchuptvandmore/resources/m3u/live_tv_it.m3u
plugin.video.catchuptvandmore/resources/m3u/live_tv_jp.m3u
plugin.video.catchuptvandmore/resources/m3u/live_tv_nl.m3u
plugin.video.catchuptvandmore/resources/m3u/live_tv_pl.m3u
plugin.video.catchuptvandmore/resources/m3u/live_tv_si.m3u
plugin.video.catchuptvandmore/resources/m3u/live_tv_tn.m3u
plugin.video.catchuptvandmore/resources/m3u/live_tv_uk.m3u
plugin.video.catchuptvandmore/resources/m3u/live_tv_us.m3u
plugin.video.catchuptvandmore/resources/m3u/live_tv_wo.m3u
tools/generate_m3u_files.py

On va bientôt passer à CodeQuick 0.9.13 avec les avantages et "inconvénients" que cela implique :
* Suppression des fonction `xxxx_bridge` du fichier `main.py`
* Modification de tous les fichiers skeleton (avec suppression de la clé `callback` dans les dictionnaires)
Le problème c'est que tout notre système M3U (que ce soit le générateur des M3U ou bien le pont entre SimplePlugin IPTV) est basé sur les deux points précédents.
Afin que le saut vers CQ 0.9.13 se fasse un peu plus en douceur, ce PR a pour but de "simplifier" tout notre système M3U actuel (donc avec CQ 0.9.12) afin de faciliter la migration à venir.
cc @wwark

Refactoring M3U system before CQ 0.9.13 update

---

plugin.video.catchuptvandmore/resources/lib/channels/wo/arte.py

Corrige trois problèmes dans arte.tv :
- nombre d'épisodes limités à 8
- épisodes mélangés entre saisons/émissions
- certaines catégories (Sciences, Histoire...) renvoient
l'erreur "No item found"

Arte TV : nombre d'épisodes limités à 8 (fix #380)

---

plugin.video.catchuptvandmore/resources/lib/channels/fr/francetv.py

Use html.unescape for Python 3.9 compatibility.

---

plugin.video.catchuptvandmore/resources/lib/main.py

Since live streams typically broadcast different content, having a
playcount is useless and even confusing. This disables playcount (and
watched indication) for live streams.

Disable playcount for live streams

---

resources/lib/channels/jp/tver.py

TVer started lazyloading their images with lazysizes (https://github.com/aFarkas/lazysizes) which results in list_videos throwing a nasty "'NoneType' object has no attribute 'get'" exception.

Fix lazily loaded images on tver.jp

---

resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.fr_fr/strings.po
resources/language/resource.language.he_il/strings.po
resources/language/resource.language.nl_nl/strings.po
tools/check_for_unused_translations.py
tools/update_translations.py

* Add scripts to update translations (see below for more info).
* Add missing NL translations.
* Fix wrong translated FR value.
* You can run `tools/update_translations.py` to update the other languages when new translations have been added or modified in the english base file.
* You can run `tools/check_for_unused_translations.py` to check the codebase for the msgctxt values. If an msgctxt doesn't exist in the codebase, it's probably not in use anymore and could be removed. I haven't done this yet in this PR. There are quite a lot of them. See [unused_translations.txt](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/6196176/unused_translations.txt)

Add scripts to manage translations and update NL translation.

---

resources/lib/resolver_proxy.py

By adding an `X-Forwarded-For` header to HTTP requests.
Before this commit, a 403 error would be returned. With this magic header, the HTTP requests work fine and return 200 instead.
Fixes #540

Fix France TV replay

---

resources/lib/channels/fr/mytf1.py

Change MYTF1 video types from lower case to upper case because of change in MyTF1 API
Fixes #562

Fix MYTF1 video types to upper case

---

resources/lib/channels/be/rtbf.py

Live aren't working anymore because they are passing by an ad service and we can't change the SAMPLE-AES by the AES-128 file...I have hardcoded the URL that is working but I don't know how long it will continue to work.

RTBF hardcode live url if it contains DRM

---

resources/lib/channels/be/rtlplaybe.py

This fix the replay issue occurring on rtl channel #576

Align with the M6 file and fix issue #576

---

resources/lib/channels/be/rtlplaybe.py

commit code again, 
partial revert of 1874564b9610c465b7b6bbc151d651d34eb1009d that removed 'all programs' menu by mistake

[BE - RTLPlay] add 'RTL Play' menu and add 'All programs' - re commit

---

resources/lib/channels/fr/mycanal.py

- URL_DEVICE_ID n'est plus accessible, donc j'ai remplacé par une autre fonction (créer par mtr81).
Ça permet de retrouver lancer de nouveau les programmes.
Je ne sais pas si la méthode de génération du DeviceId permets la lecture des DRM.
- J'ai remplacé les json.loads par la fonction json de base de requests.

Fix replay pour mycanal

---

.github/workflows/pr.yml

[Project] pr workflow: flake8 with forks

[Project] PR workflow: flake8 with forks

---

resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.fr_fr/strings.po
resources/language/resource.language.he_il/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/lib/addon_utils.py
resources/lib/channels/be/bouke.py
resources/lib/channels/be/rtbf.py
resources/lib/channels/be/rtlplaybe.py
resources/lib/channels/be/telemb.py
resources/lib/channels/be/tvlux.py
resources/lib/channels/ca/icirdi.py
resources/lib/channels/ch/latele.py
resources/lib/channels/fr/6play.py
resources/lib/channels/it/rtl.py
resources/lib/resolver_proxy.py
resources/lib/streams/m3u8.py
resources/lib/streams/mediastream.py
resources/settings.xml

resolver_proxy : get_stream_with_quality
- ajout d'un paramètre: `stream_bitrate_limit`  pour overrider la valeur de limite de bitrate uniquement dans CUTVM sans changer la config de input stream adaptive générale qui peut impacter les autres plugins kodi
- gestion de la `qualité` dans les cas où on désactive input stream adaptive
- utilisation de la valeur de la préférence `qualité` quand on utilise input stream adaptive

resolver_proxy : get_stream_with_quality

---

resources/lib/resolver_proxy.py

In the Kodi 20 version of Inpustream Adaptive, it detects the bandwidth and handle the choice of the stream automatically. It became useless for Catchup tv to do the same in this version.

Better compatibility with Kodi 20

---

resources/lib/channels/nl/npo.py

Changes this:
To this:
For shows with same-day episodes, like the news. The current sole season-episode indication makes no sense for users in this case. I opted for leaving it in the title anyway, together with the additional time indication, for consistency with other season-episode shows and in case there are shows with a useful indication anyway.
It's a bit of a nasty hack by performing a second loop, but there's unfortunately no other way to distinguish these types of shows.
Reduced code duplication in the same go.
And some cleaning-up in a separate commit.

NPO: Include time in name for same-day episodes

---

resources/lib/channels/uk/channel4.py

Successfully tested on Kodi 19.4.
The .json file already used for the video stream url also contains the subtitles url in four different formats: .ismt, .smi, .webvtt and .vtt. WebVTT appears to be supported from Kodi 20 but not on Kodi 19 so SAMI subtitles are implemented.
Not very familiar with this plugin coding style, I copied the code structure from ../be/rtlplaybe.py.

[UK - CHANNEL4] Add subtitles

---

resources/lib/channels/uk/channel4.py

Successfully tested on Kodi 19.4.
.smi subtitles were already implemented but are not always present so it makes sense to had more supported formats such as .srt subtitles and and more clever code to add more in the future. 
For example, .webvtt and .vtt subtitles are often present but not supported by Kodi 19.

[UK - CHANNEL4] Add subtitles format (.srt)

---

resources/lib/resolver_proxy.py

With v0.2.38, watching a replay video (France 3) failed with `KeyError: u'location'`.
Apparently, no redirect was performed.
This PR aims to use the URL called for redirection directly when no redirection is performed or stand with the current behaviour when there is a redirection.

Handle FranceTV stream with no redirect

---

resources/lib/channels/be/abbe.py

[BE AB] Fix live
